ZooApp/ZooApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [ 
    path('admin/', admin.site.urls),
    path('', include('zoo.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ZooApp/zoo/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.IndexView.as_view(), name='index'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('placements/', views.PlacementsIndexView.as_view(), name='placements'),
    path('registration/', views.RegistrationView.as_view(), name='registration'),
    path('animals/<int:pk>/', views.AnimalDetailView.as_view(), name='animal_detail'),
    path('post/', views.PostListView.as_view(), name='post_list'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('placements/<int:pk>/', views.PlacementsDetailView.as_view(), name='placement_detail'),
    path('employees/', views.EmployeesListView.as_view(), name='employees'),
    path('faq/', views.FAQView.as_view(), name='faq'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('certificate/', views.CertificateView.as_view(), name='certificate'),
    path('rate/', views.RateListView.as_view(), name='rate_list'),
    path('rate/create/', views.RateCreateView.as_view(), name='rate_create'),
    path('privacy/', views.TermsPrivacyView.as_view(), name='privacy'),
    path('contacts/', views.ContactsView.as_view(), name='contacts'),
    path('lab/', views.LabView.as_view(), name='lab'),
    path("vacancy/", views.VacancyView.as_view(), name="vacancy"),
    path("promo/", views.PromoView.as_view(), name="promo"),
    path("statistics/", views.StatisticsView.as_view(), name="statistics"),
    path("lab3/", views.Lab3.as_view(), name="lab3"),
    path("ads/", views.advertisement, name="ads"),
    path("anim/", views.AnimationView.as_view(), name="anim"),
    path("custom/", views.CustonView.as_view(), name="custom"),
]

ZooApp/zoo/models.py
import logging
import requests
from transliterate import translit
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.core.validators import RegexValidator


logger = logging.getLogger("main")


class Food(models.Model):  # вид корма
    food = models.CharField("food", max_length=256)

    def __str__(self):
        return self.food


class Complex(models.Model):
    complex_name = models.CharField("complex_name", max_length=128)

    def __str__(self):
        return self.complex_name


class Placement(models.Model):
    name = models.CharField("name", max_length=128, default="")
    number = models.IntegerField("number")
    reservoir = models.BooleanField("reservoir")  # наличие водоема
    heating = models.BooleanField("heating")  # наличие отопления
    complex_area = models.ForeignKey(Complex, on_delete=models.CASCADE)


class Country(models.Model):
    country = models.CharField("country", max_length=64, unique=True)

    def __str__(self):
        return self.country


class Class(models.Model):
    class_name = models.CharField("class_name", max_length=128, unique=True)

    def __str__(self):
        return self.class_name


class Kind(models.Model):
    kind = models.CharField("kind", max_length=128, unique=True)
    class_name = models.ForeignKey(Class, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.kind} ({self.class_name})"


class Animal(models.Model):
    GENDER = [("M", "Male"), ("F", "Female")]

    age = models.IntegerField("age", null=True)
    description = models.TextField("description", null=True)
    gender = models.CharField("gender", choices=GENDER, max_length=1)
    arrival_date = models.DateField("arrival_date")  # дата поступления в зоопарк
    food = models.ManyToManyField(Food)  # потребление корма
    img = models.URLField("url", null=True)
    placement = models.ForeignKey(Placement, on_delete=models.SET_NULL, null=True)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    kind = models.ForeignKey(Kind, on_delete=models.SET_NULL, null=True)  # семейство

    def __str__(self):
        return f"{self.kind.class_name} {self.kind.kind}"


class Job(models.Model):  # должности
    job_title = models.CharField("job_title", max_length=128)

    def __str__(self):
        return self.job_title


class Employee(models.Model):  # сотрудники
    firstname = models.CharField("firstname", max_length=128)
    lastname = models.CharField("lastname", max_length=128)
    patronymic = models.CharField("patronymic", max_length=128)
    phone = models.CharField("phone", max_length=32, unique=True)
    job = models.ForeignKey(Job, on_delete=models.SET_NULL, null=True)
    animals = models.ManyToManyField(Animal)
    photo = models.ImageField()

    def __str__(self):
        return f"{self.firstname} {self.lastname}"

    @property
    def gender(self):
        url = "https://api.genderize.io/?name=" + translit(
            self.firstname, language_code="ru", reversed=True
        )
        logger.info(f"Отправка запроса к API: {url}")
        response = requests.get(url)
        data = response.json()
        if data["gender"] == "male":
            return "Мужской"

        return "Женский"


class User(AbstractUser):
    employee = models.OneToOneField(Employee, on_delete=models.CASCADE, null=True)


class Client(AbstractUser):
    address = models.CharField(max_length=100)
    phone_number = models.CharField(
        validators=[
            RegexValidator(
                regex=r"^\+375 \(\d{2}\) \d{3}-\d{2}-\d{2}$",
                message="Invalid phone number.",
            )
        ],
        max_length=20,
    )

    groups = models.ManyToManyField(
        Group,
        verbose_name="groups",
        blank=True,
        help_text="The groups this user belongs to.",
        related_name="client_set",  # Добавляем related_name
    )
    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name="user permissions",
        blank=True,
        help_text="Specific permissions for this user.",
        related_name="client_set",  # Добавляем related_name
    )

    def __str__(self):
        return self.username


class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    img = models.ImageField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    changed_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Rate(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    rating = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Rate from {self.author} at {self.created_at}"


class FAQ(models.Model):
    question = models.CharField(max_length=500)
    answer = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"FAQ: {self.question} {self.created_at}"

class Settings(models.Model):
    name = models.CharField(max_length=100)
    value = models.TextField()

    def __str__(self):
        return self.value


class Ads(models.Model):
    name = models.CharField(max_length=100)
    link = models.CharField(max_length=500)
    photo = models.ImageField()

    def __str__(self):
        return self.name

ZooApp/zoo/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from zoo.models import User

class RegistrationForm(UserCreationForm):
    address = forms.CharField(max_length=100, required=True)
    phone_number = forms.CharField(max_length=11, required=True)

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        )


class RateForm(forms.Form):
    rating = forms.IntegerField(min_value=0, max_value=10)
    content = forms.CharField(widget=forms.Textarea)

ZooApp/zoo/views.py
import logging
from django.shortcuts import (
    redirect,
    render,
)
from django.contrib.auth import login
from django.conf import settings
from django.http import HttpResponse
from zoo.models import (
    FAQ,
    Ads,
    Animal,
    Client,
    Employee,
    Placement,
    Post,
    Rate,
    Settings,
)
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from zoo.forms import (
    RateForm,
    RegistrationForm,
)
import plotly.express as px

# Создаем логгер
logger = logging.getLogger("main")


class IndexView(generic.View):
    def get(self, request, *args, **kwargs):
        last_post = Post.objects.order_by("-created_at").first()
        animals = Animal.objects.all()
        placements = Placement.objects.all()
        return render(
            request,
            "animation.html",
            {
                "placements": placements,
                "animals": animals,
                "last_post": last_post,
            },
        )


class RegistrationView(generic.View):
    template_name = "registration/registration.html"

    def get(self, request, *args, **kwargs):
        form = RegistrationForm()
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)

            logger.info(f'New user {request.POST.get("username")} was added.')
            client = Client.objects.create(
                username=request.POST.get("username"),
                first_name=request.POST.get("first_name"),
                last_name=request.POST.get("last_name"),
                address=request.POST.get("address"),
                phone_number=request.POST.get("phone_number"),
            )
            client.save()

            return redirect("index")

        logger.info(f"Invalid data in the registration form.")
        return render(request, self.template_name, {"form": form})


class PostDetailView(generic.DetailView):
    template_name = "post_detail.html"
    model = Post


class PostListView(generic.ListView):
    template_name = "post_list.html"
    model = Post
    queryset = Post.objects.all().order_by("-created_at")


class AnimalDetailView(generic.DetailView):
    template_name = "animal_detail.html"
    model = Animal


class EmployeesListView(UserPassesTestMixin, generic.ListView):
    template_name = "employees.html"
    context_object_name = "employee"
    model = Employee

    def test_func(self) -> bool | None:
        return self.request.user.is_superuser

    def get_queryset(self):
        return Employee.objects.all()


class PlacementsIndexView(generic.ListView):
    template_name = "placements.html"
    context_object_name = "placements"

    def get_queryset(self):
        return Placement.objects.order_by("name")


class PlacementsDetailView(generic.DetailView):
    template_name = "animals_in_placements.html"
    model = Placement


class FAQView(generic.ListView):
    template_name = "faq.html"
    queryset = FAQ.objects.all().order_by("created_at")


class AboutView(generic.View):
    template_name = "about.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class CertificateView(generic.View):
    template_name = "certificate.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class RateCreateView(LoginRequiredMixin, generic.View):
    form_class = RateForm
    template_name = "rate_create.html"

    def get(self, request, *args, **kwargs):
        form = self.form_class()

        return render(
            request,
            self.template_name,
            {
                "form": form,
            },
        )

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            rate = Rate(
                author=request.user,
                rating=form.cleaned_data["rating"],
                content=form.cleaned_data["content"],
            )
            rate.save()
            return redirect("/rate/")

        return render(
            request,
            self.template_name,
            {
                "form": form,
            },
        )


class RateListView(generic.ListView):
    model = Rate
    template_name = "rate_list.html"


class TermsPrivacyView(generic.View):
    template_name = "terms_privacy.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class ContactsView(generic.ListView):
    model = Employee
    template_name = "contacts.html"
    queryset = Employee.objects.all()


class LabView(generic.View):
    template_name = "lab.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)
    

class CustonView(generic.View):
    template_name = "custom.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class AnimationView(generic.View):
    template_name = "animation.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class VacancyView(generic.View):
    template_name = "vacancy.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class PromoView(generic.View):
    template_name = "promo.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class StatisticsView(generic.View):
    template_name = "statistics.html"

    def get(self, request, *args, **kwargs):
        animals = Animal.objects.all().order_by("arrival_date")
        count = {}
        for animal in animals:
            count[animal.arrival_date] = count.get(animal.arrival_date, 0) + 1
        l = sorted(list(count.keys()))
        res = [count[l[0]]]
        for item in l[1:]:
            res.append(res[-1]+count[item])
        td=px.area(
            x=l,
            y=res,
            title='Arrived animals',
            labels={'x':'Date', 'y':"Count"}
        )

        posts = Post.objects.all().order_by('created_at')
        count = {}
        for animal in posts:
            print(animal.created_at)
            count[animal.created_at] = count.get(animal.created_at, 0) + 1
        l = sorted(list(count.keys()))
        res = [count[l[0]]]
        for item in l[1:]:
            res.append(res[-1]+count[item])
        hd=px.area(
            x=l,
            y=res,
            title='Created posts',
            labels={'x':'Date', 'y':"Count"}
        )
        return render(
            request,
            self.template_name,
            {
                'animals_stat': td.to_html(),
                'posts_stat': hd.to_html(),
            }
        )

class Lab3(generic.View):
    template_name = "lab3.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        interval = Settings.objects.get(id=1)
        if "interval" in request.POST.keys():
            interval.value = str(request.POST["interval"])
            interval.save()
        return render(request, self.template_name)


def advertisement(request):
    import json
    p = []
    for ad in Ads.objects.all():
        p.append({
            "name" : ad.name,
            "link" : ad.link,
            "image": ad.photo.url,
        })
    interval, created = Settings.objects.get_or_create(name="interval", defaults={"value": 5})
    l = {
        "photos": p,
        "interval": int(interval.value) * 1000
    }
    return HttpResponse(json.dumps(l), content_type="application/json")

ZooApp/zoo/templates/animals_in_placements.html
{% extends 'base.html' %}

{% block title %}
Животные в помещениях
{% endblock %}

{% block content %}
<h1>Животные {{ placement.name }}</h1>
<ul>
    {% for animal in placement.animal_set.all %}
    <li><a href="{% url 'animal_detail' animal.id %}">{{ animal }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

ZooApp/zoo/templates/animation.html
{% extends "base.html" %}

{% block title %}
Animation
{% endblock %}

{% block content %}
<h1>Zooland — главная страница</h1>
{% if request.user.is_superuser %}
<p><b>Животные: </b></p>
<table>
    <tr>
        <th>Вид</th>
        <th>Возраст, лет</th>
        <th>Пол</th>
        <th>Дата поступления</th>
    </tr>
    {% for animal in animals %}
    <tr>
        <td>{{animal.kind}}</td>
        <td>{% if animal.arrival_date %}
            {{ animal.arrival_date }}
            {% else %}
            -
            {% endif %}</td>
        <td>{% if animal.gender == 'M' %}Мужской{% else %}Женский{% endif %}</td>
        <td>{{animal.arrival_date}}</td>
    </tr>
    {% endfor %}
</table>

<br><br>
<p><b>Зоны и комлпексы: </b></p>
<table>
    <tr>
        <th>Зона</th>
        <th>Номер</th>
        <th>Резервуар</th>
        <th>Отопление</th>
        <th>Комплекс</th>
    </tr>
    {% for placement in placements %}
    <tr>
        <td>{{placement.name}}</td>
        <td>{{placement.number}}</td>
        <td>{% if placement.reservoir %} Есть {% else %} Нет {% endif %}</td>
        <td>{% if placement.heating %} Есть {% else %} Нет {% endif %}</td>
        <td>{{placement.complex_area.complex_name}}</td>
    </tr>
    {% endfor %}
    <tr>
        <td>Всего зон:</td>
        <td colspan="3">{{placements.count}}</td>
        <td></td>

    </tr>
</table>
{% else %}
{% if request.user.is_authenticated %}
<p><b>ФИО:</b> {{request.user.employee.lastname}} {{request.user.employee.firstname}} {{employee.patronymic}} </p>
<p><b>Должность:</b> {{request.user.employee.job.job_title}}</p>
<p><b>Номер телефона:</b> {{request.user.employee.phone}}</p>
<p><b>Пол:</b> {{request.user.employee.gender}}</p>
{% if request.user.employee.animals.all %}
<p><b>Работает со следующими животными: </b></p>
<table>
    <tr>
        <th>Вид</th>
        <th>Возраст, лет</th>
        <th>Пол</th>
        <th>Дата поступления</th>
        <th>Зона</th>
        <th>Номер зоны</th>
        <th>Комплекс</th>
    </tr>
    {% for animal in request.user.employee.animals.all %}
    <tr>
        <td>{{animal.kind.kind}}</td>
        <td>{% if animal.age %}{{animal.age}}{% else %}—{% endif %}</td>
        <td>{% if animal.gender == 'M' %}Мужской{% else %}Женский{% endif %}</td>
        <td>{% if animal.arrival_date %}
            {{ animal.arrival_date }}
            {% else %}
            -
            {% endif %}</td>
        <td>{{animal.placement.name}}</td>
        <td>{{animal.placement.number}}</td>
        <td>{{animal.placement.complex_area.complex_name}}</td>
    </tr>
    {% endfor %}
</table>

<br><br>
<p><b>Питание:</b></p>
<table>
    <tr>
        <th>Вид</th>
        <th>Чем кормить</th>
    </tr>
    {% for animal in request.user.employee.animals.all %}
    <tr>
        <td>{{animal.kind.kind}}</td>
        <td>
            <ul>
                {% for food in animal.food.all %}
                <li>{{food.food}}</li>
                {% endfor %}
            </ul>
        </td>
    </tr>
    {% endfor %}
</table>
{% endif %}
{% endif %}
<h2>Животные зоопарка: </h2>
<p><b>Всего видов:</b> {{animals.count}}</p>
<br>
<table>
    <tr>
        <th>Вид (Класс)</th>
        <th>Возраст, лет</th>
        <th>Страна</th>
        <th>Описание</th>
        <th>Подробнее</th>
    </tr>
    {% for animal in animals %}
    <tr>
        <td>{{animal.kind}}</td>
        <td>{% if animal.age %}
            {{animal.age}}
            {% if animal.age == 1 %}
            год
            {% elif animal.age > 4 %}
            лет
            {% else %}
            года
            {% endif %}
            {% else %}
            -
            {% endif %}</td>
        <td>{{animal.country.country}}</td>
        <td>{{animal.description}}</td>
        <td><a href="{% url 'animal_detail' animal.id %}">Link</a></td>
    </tr>
    {% endfor %}
</table>
{% endif %}
<h2>Last news</h2>
<hr>
<article class="last-post">
    <h3>
        {{last_post.title}} <span class="post-time">{{last_post.created_at}}</span>
    </h3>
    <div class="content">
        {% if last_post.img %}
        <img width="200px" src="/media/{{ last_post.img }}">
        {% endif %}
        <p>
            {{last_post.content|truncatewords:7}}
            <br>
            <a href="{% url 'post_detail' last_post.pk%}">Читать далее...</a>
        </p>
    </div>
</article>
<hr>
{% include "includes/advertise.html" %}
{% endblock %}

{% block extra_content %}
<style>
    #tree_left,
    #tree_right {
        top: 200px;
        width: 80%;
        height: auto;
    }

    .test {
        width: 100vw;
        height: 130vh;
    }


    #top {
        position: relative;
        width: 100%;
        height: 100%;
        overflow: hidden;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    #top::before {
        content: '';
        position: absolute;
        bottom: 0;
        left: 0;
        height: 200px;
        width: 100%;
        background: linear-gradient(to top, #fff, transparent);
        z-index: 1000;
    }

    #man {
        top: inherit;
        bottom: 0;
        width: auto;
    }

    section img {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        object-fit: cover;
        pointer-events: none;
    }

    #text {
        position: relative;
        color: white;
        font-size: 10rem;
    }
</style>
<div class="test">
    <section id="top">
        <img src="/static/zoo/img/anim-bg.jpeg" id="bg" />
        <h2 id="text">Zoopark</h2>
        <img src="/static/zoo/img/family.png" id="man" />
        <img src="/static/zoo/img/tree.png" id="tree_left" />
        <img src="/static/zoo/img/tree.png" id="tree_right" />
    </section>

</div>
{% endblock %}

{% block scripts %}
<script>

    const treeLeft = document.querySelector('#tree_left');
    const treeRight = document.querySelector('#tree_right');
    const cloud1 = document.querySelector('#clouds_1');
    const cloud2 = document.querySelector('#clouds_2');
    const text = document.querySelector('#text');
    const man = document.querySelector('#man');


    window.addEventListener("load", () => {
        let value = scrollY;
        treeLeft.style.left = `calc(-${+value / 0.7}px - 30%)`
        treeRight.style.left = `calc(50% + ${value / 0.7}px)`
        text.style.bottom = `-${value}px`;
        man.style.height = `${window.innerHeight - value / 0.7}px`
        man.style.left = `calc(50% - ${man.getBoundingClientRect().width / 2}px)`
        man.style.top = `calc(100% + ${value - man.getBoundingClientRect().height}px)`
    })
    window.addEventListener('scroll', () => {
        let value = scrollY;
        treeLeft.style.left = `calc(-${+value / 0.7}px - 30%)`
        treeRight.style.left = `calc(50% + ${value / 0.7}px)`
        text.style.bottom = `-${value}px`;
        man.style.height = `${window.innerHeight - value / 0.7}px`
        man.style.left = `calc(50% - ${man.getBoundingClientRect().width / 2}px)`
        man.style.top = `calc(100% + ${value - man.getBoundingClientRect().height}px)`
    })
</script>
{% endblock %}

ZooApp/zoo/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <script>
        function updateDateTime() {
            var currentDateTime = new Date();
            var formattedDateTime = currentDateTime.toLocaleString();
            var element = document.getElementById("current-datetime");
            element.innerHTML = formattedDateTime;
        }
        setInterval(updateDateTime, 1000);
    </script>
    <link rel="stylesheet" href="{% static 'zoo/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'zoo/css/blackjack.css' %}">
    <link rel="icon" type="image/png" href="{% static 'zoo/img/Logo.svg' %}"/>
</head>

<body>
    {% include 'includes/header.html' %}
    {% block extra_content %}
    {% endblock %}
    <main>
        {% block content %}
        {% endblock %}
    </main>
    {% include 'includes/footer.html' %}
</body>
    {% block scripts %}{% endblock %}
    <script src="{% static 'zoo/js/main.js' %}"></script>
</html>

ZooApp/zoo/templates/certificate.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Certificate
{% endblock %}

{% block content %}
<section class="certificate">
    <div class="bg"></div>
    <div class="border-img"></div>
    <!-- <img src="{% static 'zoo/img/gg.png' %}" alt="" class="border-img"> -->
    <div class="header">
        <p class="name">Certificate</p>
        <img src="{% static 'zoo/img/Logo.svg' %}" alt="" width="100px" height="100px">
    </div>
    <div class="body">
        <p>Given to <span class="company">Prodigy</span> for compliance with the quality of products.</p>
        <p>Issued by the Ministry of Quality</p>
    </div>
    <!-- <p>Given to the company <span class="company">Prodigy</span></p> -->
    <div class="footer">
        <p class="record">record <span class="number">i712346</span></p>
        <p class="sign">Mr. Siegal | Minister of Quality</p>
    </div>
</section>
{% endblock %}

ZooApp/zoo/templates/contacts.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Contacts
{% endblock %}

{% block content %}
<h1>Contacts</h1>
    {% for employee in object_list %}
    <figure style="display: flex; flex-direction: row;">
        {% if employee.photo %}
            <img style="width:300px;" src="{{employee.photo.url}}" alt="" />
        {% else %}
            <img style="width: 300px;" src="{% static 'zoo/img/Logo.svg' %}">
        {% endif %}
        <figcaption>
            <ul style="font-size: 15pt;">
                <li>{{employee.lastname}}</li>
                <li>{{employee.firstname}}</li>
                <li>{{employee.patronymic}}</li>
                <li>{{employee.job}}</li>
                <li><a href="tel: {{employee.phone}}">{{employee.phone}}</a></li>
            </ul>
        </figcaption>
    </figure>
    {% endfor %}
{% endblock %}

ZooApp/zoo/templates/employees.html
{% extends 'base.html' %}

{% block title %}
Employees
{% endblock %}

{% block content %}
<p><b>Сотрудники: </b></p>
<table>
    <tr>
        <th>ФИО</th>
        <th>Должность</th>
        <th>Номер телефона</th>
    </tr>
    {% for emp in employee %}
    <tr>
        <td>{{emp.lastname}} {{emp.firstname}} {{emp.patronymic}}</td>
        <td>{{emp.job.job_title}}</td>
        <td>{{emp.phone}}</td>
    </tr>
    {% endfor %}

</table>
{% endblock %}

ZooApp/zoo/templates/faq.html
{% extends "base.html" %}

{% block title %}
FAQ
{% endblock %}

{% block content %}
<h1><abbr title="Frequently Asked Questions">FAQ</abbr></h1>
<section class="faq">
    {% for faq in object_list %}
    <details>
        <summary>{{faq.question}} (задан {{faq.created_at}})</summary>
        {{faq.answer|safe}}
    </details>
    {% endfor %}
{% endblock %}

ZooApp/zoo/templates/post_detail.html
{% extends "base.html" %}

{% block title %}
{{object.title}}
{% endblock %}

{% block content %}
<article itemscope itemtype="http://schema.org/Article" class="post-detail">
    <h3 itemprop="name">{{object.title}}</h3>
    <meta itemprop="inLanguage" content="ru" /> 
    <img src="/media/{{object.img}}" alt="">
    <p itemprop="articleBody">
        {{object.content}}
    </p>
</article>
{% endblock %}

ZooApp/zoo/templates/statistics.html
{% extends "base.html" %}

{% block title %}
Statistics
{% endblock %}

{% block content %}
{{animals_stat|safe}}
{{posts_stat|safe}}
{% endblock %}